version: "3.9"

services:
  db:
    image: mariadb:10.6
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: whaticket
      MYSQL_USER: whaticket
      MYSQL_PASSWORD: supersecretpassword
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: America/Bogota
    volumes:
      - whatpro-db:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:6
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - whatpro-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  backend:
    build:
      context: https://github.com/Juanda84/what-pro.git#master:backend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      TZ: America/Bogota
      DB_HOST: db
      DB_USER: whaticket
      DB_PASS: supersecretpassword
      DB_NAME: whaticket
      REDIS_URI: redis://redis:6379
      JWT_SECRET: myjwtsecret
      FRONTEND_URL: http://72.60.169.104:3000
      PORT: "8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    # ✔ Todo en una sola línea
    command: >
      sh -lc "dockerize -wait tcp://db:3306 -timeout 60s && npx sequelize db:migrate --config dist/config/database.js --migrations-path dist/database/migrations && node dist/server.js"
    ports:
      - "8081:8080"
    volumes:
      - whatpro-media:/usr/src/app/public
    shm_size: "1gb"
    restart: unless-stopped

  frontend:
    build:
      context: https://github.com/Juanda84/what-pro.git#master:frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://72.60.169.104:8081
      REACT_APP_BACKEND_URL: http://72.60.169.104:8081
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  whatpro-db:
  whatpro-redis:
  whatpro-media:

